### PR TITLE
AR Driving Car Demo 

### PR DESCRIPTION
**Pull request by equationalapplications**
Update to run with the newest starter-kit configuration.
Adapted from original code from here: 
https://github.com/viromedia/viro/tree/master/js/ARDrivingCarDemo

## Issues

Mulit-touch is not working on Android, so you can't control the steering wheel and the pedals at the same time.

Also has a yellow console warning:
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

### CODE REVIEW

**Comment by geo-vi** [comment]
Sick! Will check it out asap

From what I could review so far the code looked well ))

**Comment by equationalapplications** [comment]
Let me know if you have any suggestions or things you think I should fix. Thanks!

**Comment by adelarsq** [comment]
@equationalapplications Thanks for the contribution 👏🏻
@geo-vi Thanks for the review bro 👊🏻

**Comment by equationalapplications** [comment]
You're welcome! I hope to be able to contribute some more :)

**Pull request merged**
